name: eastwoo's blog
url: yingtaojuzi.github.io
description: Recording interesting things in this blog

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
